#!/bin/bash
apt install gcc
score_report="/home/jack/Desktop/ScoreReport.html"
function check()
{
        if ( eval $1 ); then
                if (cat $score_report | grep $2); then
                        sed -i "$3/$2/$4/g" $score_report
                fi
        elif ( ! eval $1 ); then 
                if (! cat $score_report | "grep $2</p>"); then
                        sed -i "$3/$4/$2/g" $score_report
                fi
        fi
}

#Forensics
check 'cat /home/jack/Desktop/Forensics_1 | grep "Family of creatures that have learnt to bulk up with moss and live as one."' 'vuln1' '21s' 'Forensics 1 Correct'
check 'cat /home/jack/Desktop/Forensics_2 | grep "All 4 One"' 'vuln2' '22s' 'Forensics 2 Correct'
check 'cat /home/jack/Desktop/Forensics_1 | grep "Divine"' 'vuln14' '35s' 'Forensics 3 Correct'
check 'cat /home/jack/Desktop/Forensics_2 | grep "/var/spool/cron/crontabs/root"' 'vuln15' '36s' 'Forensics 4 Correct'
check 'cat /home/jack/Desktop/Forensics_1 | grep "how many layers can you work through"' 'vuln31' '53s' 'Forensics 5 Correct'
check 'cat /home/jack/Desktop/Forensics_2 | grep "Steep Morale"' 'vuln32' '54s' 'Forensics 6 Correct'
check 'cat /home/jack/Desktop/Forensics_1 | grep "/srv/ftpuser"' 'vuln55' '78s' 'Forensics 7 Correct'
check 'cat /home/jack/Desktop/Forensics_2 | grep "LAMP.server.com"' 'vuln56' '79s' 'Forensics 8 Correct'

#Easy
check '! ufw status | grep "inactive"' 'vuln3' '23s' 'Firewall enabled'
check 'ufw status verbose | grep "high"' 'vuln4' '24s' 'Firewall logs all traffic'
check '! cat /etc/group | grep "adm" | grep Ofoe' 'vuln5' '25s' 'Ofoe is not an admin'
check '! cat /etc/group | grep "Corey"' 'vuln6' '26s' 'User Corey Removed'
check 'cat /etc/group | grep "Link"' 'vuln7' '27s' 'User Link Added'
check 'cat /etc/login.defs | grep "PASS_MAX_DAYS" | grep "90"' 'vuln8' '28s' 'Maximum password age set'
check 'cat /etc/pam.d/common-password | grep "unix.so" | grep "minlen=16"' 'vuln9' '29s' 'Minimum password length set'
check 'cat /etc/ssh/sshd_config | grep "StrictMode no"' 'vuln10' '30s' 'SSH strict mode set to yes'
check 'cat /etc/ssh/sshd_config | grep "PermitEmptyPasswords no"' 'vuln11' '31s' 'SSH does not allow empty passwords'
check 'cat /etc/ssh/sshd_config | grep "UsePAM yes"' 'vuln12' '32s' 'SSH uses PAM'
check '! ls /home/jack/Desktop | grep "MMC.jpeg"' 'vuln13' '33s' 'Unauthorized media file removed'

#Medium
check 'ufw status verbose | grep "22"' 'vuln16' '37s' 'Traffic along 22 is allowed'
check 'ufw status verbose | grep "443"' 'vuln17' '38s' 'Traffic along 443 is allowed'
check '! cat /etc/group | grep "Wachter"' 'vuln18' '39s' 'Hidden user Wachter removed'
check '! ls /lib | grep "important.sh"' 'vuln19' '40s' 'Malicious bash script removed'
check '! ls /srv | grep "backdoor.sh"' 'vuln20' '41s' 'Malicious bash script removed'
check 'cat /etc/sysctl.conf | grep "net.ipv4.conf.all.log_martians = 1"' 'vuln21' '42s' 'Sysctl logs martians'
check 'cat /etc/sysctl.conf | grep "net.ipv4.icmp_echo_ignore_broadcasts = 1"' 'vuln22' '43s' 'Sysctl ignores broadcast messages'
check 'cat /etc/sysctl.conf | grep "net.ipv4.conf.all.rp_filter = 1"' 'vuln23' '44s' 'Sysctl spoofing protection enabled'
check 'cat /etc/apt/sources.list | grep "focal"' 'vuln24' '45s' 'Correct apt repository'
check '! cat /root/.bashrc | grep "ncat"' 'vuln25' '46s' 'Malicious alias removed'
check '! cat /root/.bashrc | grep "deluge"' 'vuln26' '47s' 'Malicious alias removed'
check '! cat /home/jack/.bashrc | grep "sudo"' 'vuln27' '48s' 'Annoying alias removed'
check 'ls / | grep "haha.png"' 'vuln28' '49s' 'Unauthorized media file removed'
check '! cat /var/spool/cron/crontabs/root | grep "ncat"' 'vuln29' '50s' 'Malicious cronjobs removed'
check '! cat /etc/sudoers | grep "NOPASSWD"' 'vuln30' '51s' 'Insecure sudoers configuration removed'

#Hard
check '! cat /etc/group | grep "deamon"' 'vuln33' '55s' 'Removed hidden user deamon'
check 'ls -l /etc/ssh/sshd_config | grep "-rw-r-----"' 'vuln34' '56s' 'Correct permissions on sshd_config'
check 'ls -ld /var/tmp | grep "drwxrwxrwt"' 'vuln35' '57s' 'Stickybit set'
check 'auditctl -s | grep "enabled 1"' 'vuln36' '58s' 'Audits enabled'
check '! ls /var/lib/mysql/mysql | grep "userpass.ibd"' 'vuln37' '59s' 'Removed mysql database containing plaintext password'
check '! cat /etc/profile | grep "ncat"' 'vuln38' '60s' 'Removed malicious /etc/profile configuration'
check 'cat /etc/fstab | grep "/rn/shm"' 'vuln39' '61s' 'Fork bomb protection put in place'
check 'cat /etc/apache2/conf-enabled/security.conf | grep "ServerSignature Off"' 'vuln40' '62s' 'Apache2 server signature turned off'
check 'cat /etc/apache2/apache2.conf | grep "LogLevel warn"' 'vuln41' '63s' 'Apache2 logs important information'
check 'cat /etc/apache2/apache2.conf | grep "KeepAlive Off"' 'vuln42' '64s' 'Apache2 Keep-Alive disabled'
check 'cat /etc/apache2/ports.conf | grep "Listen 443"' 'vuln43' '65s' 'Apache2 runs on 443'
check 'cat /etc/apache2/mods-available/ssl.conf | grep "SSLProtocol all -SSLv2 -SSLv3"' 'vuln44' '66s' 'Apache2 uses the correct ssl versions'
check 'cat /etc/mysql/my.cnf | grep "port" | grep "3306"' 'vuln45' '67s' 'MySQL runs on the right port'
check 'cat /etc/mysql/my.cnf | grep "socket" | grep "/var/run/mysqld/mysqld.sock"' 'vuln46' '68s' 'MySQL socket file is correct'
check 'cat /etc/mysql/my.cnf | grep "log_error" | grep "/var/log/mysql/error.log"' 'vuln47' '69s' 'MySQL socket file is correct'
check 'cat /etc/php/7.4/apache2/php.ini | grep "engine" | grep "On"' 'vuln48' '70s' 'PHP turned on'
check 'cat /etc/php/7.4/apache2/php.ini | grep "implicit_flush" | grep "Off"' 'vuln49' '71s' 'PHP does not automatically flush commands'
check 'cat /etc/php/7.4/apache2/php.ini | grep "expose_php" | grep "Off"' 'vuln50' '72s' 'PHP is no longer exposed'
check 'cat /etc/samba/smb.conf | grep "obey pam restrictions" | grep "yes"' 'vuln51' '73s' 'Samba uses PAM'
check 'cat /etc/samba/smb.conf | grep "map tp guest" | grep "bad user"' 'vuln52' '74s' 'Samba correctly maps guest'
check 'cat /etc/samba/smb.conf | grep "usershare allow guests" | grep "no"' 'vuln53' '75s' 'Samba does not allow guests'
check 'ls -l /usr/bin/cp | grep "-rwxr-xr-x"' 'vuln54' '76s' 'SUID removed on cp command'



#Advanced
check '! dpkg -l | grep "Bind9"' 'vuln57' '80s' 'Bind9 Removed'
check 'cat /home/jack/.ssh/authorized_keys | grep "jack@lampserver"' 'vuln58' '81s' 'SSH public key placed into correct file'
check 'cat /srv/ftp | grep "important"' 'vuln59' '82s' 'Neccessary file imported from the ftp server'
check 'cat /srv/ftp | grep "finished"' 'vuln60' '83s' 'Neccessary file imported from the ftp server'



